---
# A conda environment with all useful package for simtools developers
name: simtools-dev
channels:
  - conda-forge
dependencies:
  - python=3.12
  - adjustText
  - astropy-base
  - boost-histogram
  - ctao-dpps-cosmic-ray-spectra
  - ctapipe-base
  - eventio
  - h5py
  - jsonschema
  - matplotlib-base
  - myst-parser
  - numpy
  - numpydoc
  - particle
  - pip
  - pre-commit
  - pydata-sphinx-theme
  - pylint
  - pymongo
  - pyproj
  - pytest
  - pytest-cov
  - pytest-mock
  - pytest-profiling
  - pytest-repeat
  - pytest-xdist
  - python-dotenv
  - pyyaml
  - ruff
  - scipy
  - sphinx
  - sphinx-design
  - towncrier
  - toml
  - pip:
      - pytest-random-order
      - pytest-requirements
      - pytest-retry

# cheatsheet
# create: conda env create -f environment.yml
# activate: conda activate simtools-dev
# update (conda/mamba): conda env update -f environment.yml --prune
# update (micromamba): micromamba update -f environment.yml
