# A conda environment with all useful package for simtools developers
name: simtools-dev
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pyyaml
  - numpy
  - astropy
  - matplotlib-base
  - pre-commit
  - pytest
  - pytest-cov
  - scipy
  - pymongo
  - numpydoc
  - sphinx
  - sphinx_rtd_theme
  - pyproj
  - pyflakes
  - eventio
  - boost-histogram
  - jsonschema
  - h5py

# cheatsheet
# create: conda env create -f environment.yml
# activate: conda activate simtools-dev
# update: conda env update -f environment.yml --prune
