# A conda environment with all useful package for ctamclib developers
name: gammasim-tools-dev
dependencies:
  - pyyaml
  - numpy
  - astropy
  - matplotlib
  - sphinx
  - pytest
  - pytest-cov
  - scipy

# cheatsheet

# create: conda env create -f environment.yml
# activate: conda activate gammasim-tools-dev
# update: conda env update -f environment.yml --prune
