---
name: build-simtel_array
# Build and push sim_telarray images.
#
# The images are built and pushed when manually triggered (workflow_dispatch).
#

on:
  workflow_dispatch:
  pull_request:
    paths:
      - docker/Dockerfile-simtel_array
  schedule:
    - cron: '0 0 1 * *'  # Every 1st day of the month at 00:00 UTC (build only)

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  CLOUD_URL: "https://syncandshare.desy.de/index.php/s/"

jobs:
  build-sim_telarray:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        version:
          - {simtel_version: 'v2025-11-30-rc', hessio_version: 'v2025-12-01-rc', stdtools_version: 'v2025-06-16-rc'}
    env:
      BASE_LABEL: "sim_telarray"
      BASE_TAG: "${{ matrix.version.simtel_version }}"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          tags: |
            type=raw,value=${{ env.BASE_TAG }}
            type=ref,event=pr,suffix=-${{ env.BASE_TAG }}
            type=semver,pattern={{major}}.{{minor}}.{{patch}}-${{ env.BASE_TAG }}
            type=schedule,pattern={{date 'YYYYMMDD'}}-${{ env.BASE_TAG }}
          images: ${{ env.REGISTRY }}/gammasim/${{ env.BASE_LABEL }}
          flavor: latest=true

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: 'linux/amd64,linux/arm64/v8'
          build-args: |
            SIMTEL_VERSION=${{ matrix.version.simtel_version }}
            HESSIO_VERSION=${{ matrix.version.hessio_version }}
            STDTOOLS_VERSION=${{ matrix.version.stdtools_version }}
          secrets: |
            sim_telarray_token=${{ secrets.SIMTELARRAY_CTAO_GITLAB }}
            hessio_token=${{ secrets.HESSIO_CTAO_GITLAB }}
            stdtools_token=${{ secrets.STDTOOLS_CTAO_GITLAB }}
          push: ${{ github.event_name == 'workflow_dispatch' }}
          file: ./docker/Dockerfile-simtel_array
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
