---
name: build-simtools-dev
# Build simtools images for developers based on CORSIKA / sim_telarray images (no optimizations)

on:
  workflow_dispatch:
  pull_request:
    paths:
      - docker/Dockerfile-simtools-dev
  release:
    types: [published]
  schedule:
    - cron: '0 0 * * 0'  # Every Sunday at 00:00 UTC (build only)

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  CLOUD_URL: "https://syncandshare.desy.de/index.php/s/"

jobs:

  download-qgsjet-tables:
    runs-on: ubuntu-latest
    steps:
      - name: Download QGSJet
        run: |
          wget --no-verbose ${{ env.CLOUD_URL }}/${{ secrets.CLOUD_QGSJET3 }}/download -O qgsdat-III.bz2
      - name: Upload QGSJet files
        uses: actions/upload-artifact@v5
        with:
          name: upload-qgsjet-tables
          path: |
            qgsdat-III.bz2
          retention-days: 1

  build-simtools-dev:
    runs-on: ubuntu-latest
    needs: [download-qgsjet-tables]
    permissions:
      contents: read
      packages: write
    env:
      BASE_LABEL: "simtools-dev"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Download QGSJet tables
        uses: actions/download-artifact@v6
        with:
          name: upload-qgsjet-tables
          path: .

      - name: Set build branch
        run: |
          if [[ "${{ github.event_name }}" == 'pull_request' ]]; then
            echo "SIMTOOLS_BRANCH=${GITHUB_HEAD_REF}" >> "$GITHUB_ENV"
          else
            echo "SIMTOOLS_BRANCH=${GITHUB_REF#refs/heads/}" >> "$GITHUB_ENV"
          fi
          echo "BUILD BRANCH ${{ env.SIMTOOLS_BRANCH }}"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          tags: |
            type=ref,event=pr
            type=semver,pattern={{major}}.{{minor}}.{{patch}}
            type=schedule,pattern={{date 'YYYYMMDD'}}
            type=raw,value={{date 'YYYYMMDD'}}
          images: ${{ env.REGISTRY }}/gammasim/${{ env.BASE_LABEL }}
          flavor: latest=true

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64/v8
          build-args: SIMTOOLS_BRANCH=${{ env.SIMTOOLS_BRANCH }}
          push: ${{ github.event_name == 'release' || github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch' }}
          file: ./docker/Dockerfile-simtools-dev
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
